name: client
description: Realtime frontend.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  logging: ^1.0.2
  shared:
    path: ../shared
  web_socket_channel: ^2.2.0
  playcanvas:
    path: ../../../playcanvas
  # FIXME: If package:playcanvas exposed a fully darty api we would
  # not need to depend on package:js.
  js: ^0.6.4

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0