name: shimmer2_server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  shimmer2_shared:
    path: ../shimmer2_shared

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
