name: server
description: Backend for realtime example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  shelf: ^1.3.2
  shelf_web_socket: ^1.0.2
  shared:
    path: ../shared
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0